spring:
  application:
    name: ms-counter

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: latest
      enable-auto-commit: true
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.lanit.edp.deserializer.CustomDeserializer
      heartbeat-interval-ms: '6000'

  datasource:
    url: jdbc:postgresql://localhost:5432/counter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:db.changelog-master.xml

server.port: 8081

app:
  kafka:
    topic:
      wordCounterRequest: word-counter.request